import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "dotenv/config"
import ReduxWrapper from "@/components/providers/ReduxWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxWrapper>
        <body className={inter.className}>{children}</body>
      </ReduxWrapper>
    </html>
  );
}
